---
- name: Install packages
  hosts: all
  become: true

  tasks:
    - name: Install docker
      apt:
        update_cache: yes
        name: docker.io 

    - name: Add the user jenkins to Docker group
      user:
        name: jenkins
        group: docker
        state: present
      notify: 
        - Restart VM
  
  handlers:
    - name: Restart VM
      reboot: